### ISSUE TITLE
Fix: Adding style on quiz container

### ISSUE THREAD

**Issue by yube01** [Sar-taj107/Tech-Quiz#27]
Quiz container seems quite big we can add some padding and margin for better UI

**Comment by Sar-taj107** [comment]
sure @yube01 thanks for showing your interest to work on this repo please go ahead start contributing & create a PR!
yes, i will merge it

happy hacking^^

**Comment by yube01** [comment]
Can you add hacktoberfest-accepted label in this issue and assign it to me

**Comment by Sar-taj107** [comment]
oki! now start contributing.

**Comment by Atheke** [comment]
I would like to suggest making the modals more translucent to match with the color  changing theme can i contribute to this

**Comment by Sar-taj107** [comment]
Yes, @Atheke why not you can add/improve more feature or effective UI appealing transition  but make sure without effecting the existing code. 
Thanks for query!
