### ISSUE TITLE
Fix: Making the site responsive

### ISSUE THREAD

**Issue by DeepRahangdale** [Sar-taj107/Tech-Quiz#33]
For the Medium and small screen the question card get hide

**Comment by Sar-taj107** [comment]
yeah @DeepRahangdale  you're correct,  but now this problem not be there coz currently i have update the code. yes you can make it more responsive to fit/support different screen size it will be more better for the user experience.

Thanks for showing your interest just start contributing 🚀!

**Comment by DeepRahangdale** [comment]
yeah!! now its looks responsive so no need of further Chnages
